version: "3.6"

services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_DB: gift_cards_${ENV:-development}

  hasura:
    image: hasura/graphql-engine:latest.cli-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/gift_cards_${ENV:-development}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: "{\r\n  \"type\": \"HS256\",\r\n  \"key\": \"tXkNtKBfFpcu4Ac3GENggguWvFR9JFblo3ef\",\r\n  \"claims_format\": \"json\"\r\n}"
    volumes:
      - ./hasura/hasura-migrations:/hasura-migrations

  knex:
    build:
      context: .
      dockerfile: Dockerfile.knex
    depends_on:
      - "postgres"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:@postgres:5432/gift_cards_${ENV:-development}

  authentication:
    image: ruby:2.7.0-alpine3.11
    command:
      - /bin/sh
      - -c
      - |
        cd /app
        gem install bundler
        bundle install
        ruby ./generate_auth_token.rb
    volumes:
      - ./authentication:/app:delegated
