version: 2.0
jobs:
  build:
    working_directory: ~/app
    docker:
      # First image is the primary image
      - image: circleci/node:12.0.0
        environment:
          NODE_ENV: test
          DATABASE_URL: postgres://circleci@localhost:5432/gift_cards_test

      - image: postgres:12.1-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: gift_cards_test

      - image: hasura/graphql-engine:latest.cli-migrations
        environment:
          HASURA_GRAPHQL_DATABASE_URL: postgres://circleci@localhost:5432/gift_cards_test
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
          HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
          HASURA_GRAPHQL_JWT_SECRET: "{\r\n  \"type\": \"HS256\",\r\n  \"key\": \"tXkNtKBfFpcu4Ac3GENggguWvFR9JFblo3ef\",\r\n  \"claims_format\": \"json\"\r\n}"
          AWAIT_DATABASE_STARTUP: 20
        entrypoint: [.circleci/circleci-hasura-entrypoint.sh]

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --network-concurrency 1 --frozen-lockfile
      - save_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: run database migrations
          command: yarn knex migrate:latest --env test
      - run:
          name: Run all tests
          command: yarn jest
