version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          command: |
            set -x
            make init
      - run:
          command: |
            set -x
            make test
