version: 2.0
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --network-concurrency 1
      - save_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: test
          command: yarn jest
